variables:
  AWS_DEFAULT_REGION: eu-west-2
  BUCKET_NAME: spendy.xyz

build:
  stage: build
  image: node:alpine
  cache:
    paths:
      - src/ui/node_modules/
  script:
    - cd src/ui/
    - npm install
    - npm run build
  artifacts:
    paths:
      - src/ui/build/
    expire_in: 1 hour

test:
  stage: test
  image: node:alpine
  cache:
    paths:
      - src/ui/node_modules/
  script:
    - cd src/ui/
    - npm install
    - CI=true npm test

deploy_prod:
  stage: deploy
  dependencies:
    - build
  image: python:alpine
  script:
    - 'which awscli || (pip install awscli)'
    - aws s3 sync ./src/ui/build/ s3://${BUCKET_NAME} --delete
  environment:
    name: production
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/
  only:
    - master

